/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF8/rtJN6pwgUQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF8/rtJN6pwgUQ= >>
// ----------- >>
public class Amministrative extends Employee {
// ----------- << class.extras@AAAAAAF8/rtJN6pwgUQ= >>
// ----------- >>
}