/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF8/sPJ+blOSpk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF8/sPJ+blOSpk= >>
// ----------- >>
public class Commitment {
    // ----------- << attribute.annotations@AAAAAAF8/sQ2K7qh8Ig= >>
    // ----------- >>
    private Integer nHours;

    public Integer getNHours() {
        return nHours;
    }

    public void setNHours(Integer nHours) {
        this.nHours = nHours;
    }

// ----------- << class.extras@AAAAAAF8/sPJ+blOSpk= >>
// ----------- >>
}