/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF8/qzMhaG4Qrk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF8/qzMhaG4Qrk= >>
// ----------- >>
public class Faculty {
    // ----------- << attribute.annotations@AAAAAAF8/rU+z6TmpNA= >>
    // ----------- >>
    private String name;

    // ----------- << attribute.annotations@AAAAAAF8/q1jQ6ISZNQ= >>
    // ----------- >>
    private University ateneo;

    // ----------- << attribute.annotations@AAAAAAF8/rEiSKNPkoo= >>
    // ----------- >>
    private Set<Institute>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF8/rkuEaauWg0= >>
    // ----------- >>
    private Employee ;

    public String getName() {
        return name;
    }

    public University getAteneo() {
        return ateneo;
    }

    public Set<Institute> get() {
        return ;
    }

    public Employee get() {
        return ;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setAteneo(University ateneo) {
        this.ateneo = ateneo;
    }

    public void set(Employee ) {
        this. = ;
    }

    public void linkAteneo(University _ateneo) {
        if (_ateneo != null) {
            _ateneo.getFaculties().add(this);
        }

        unlinkAteneo();
        setAteneo(_ateneo);
    }

    public void link(Institute _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void link(Employee _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlinkAteneo() {
        if (getAteneo() != null) {
            getAteneo().getFaculties().remove(this);
            setAteneo(null);
        }
    }

    public void unlink(Institute _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Institute _, Iterator<Institute> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF8/qzMhaG4Qrk= >>
// ----------- >>
}