/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF8/q0R0KHkzhg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF8/q0R0KHkzhg= >>
// ----------- >>
public class Institute {
    // ----------- << attribute.annotations@AAAAAAF8/rYDuqU8ROI= >>
    // ----------- >>
    private String Address;

    // ----------- << attribute.annotations@AAAAAAF8/rD5oKLUyAI= >>
    // ----------- >>
    private Institute ;

    // ----------- << attribute.annotations@AAAAAAF8/rD5oKLT80M= >>
    // ----------- >>
    private Institute ;

    // ----------- << attribute.annotations@AAAAAAF8/rEiSKNQmX8= >>
    // ----------- >>
    private Set<Faculty>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF8/r0SaK44ByE= >>
    // ----------- >>
    private Researcher ;

    public String getAddress() {
        return Address;
    }

    public Institute get() {
        return ;
    }

    public Institute get() {
        return ;
    }

    public Set<Faculty> get() {
        return ;
    }

    public Researcher get() {
        return ;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    public void set(Institute ) {
        this. = ;
    }

    public void set(Institute ) {
        this. = ;
    }

    public void set(Researcher ) {
        this. = ;
    }

    public void link(Institute _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Institute _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Faculty _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void link(Researcher _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(Faculty _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Faculty _, Iterator<Faculty> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF8/q0R0KHkzhg= >>
// ----------- >>
}