/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF8/sZL6ruK+Mo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF8/sZL6ruK+Mo= >>
// ----------- >>
public class Lecturer extends Researcher {
    // ----------- << attribute.annotations@AAAAAAF8/seFdL5hT+A= >>
    // ----------- >>
    private Set<Course>  = new HashSet<>();

    public Set<Course> get() {
        return ;
    }

    public void link(Course _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlink(Course _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Course _, Iterator<Course> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF8/sZL6ruK+Mo= >>
// ----------- >>
}