/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF8/r/qwrJQKOM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF8/r/qwrJQKOM= >>
// ----------- >>
public class Project {
    // ----------- << attribute.annotations@AAAAAAF8/sAr4LKrrCI= >>
    // ----------- >>
    private Set<Researcher>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF8/sMsqbVu74M= >>
    // ----------- >>
    private Project ;

    // ----------- << attribute.annotations@AAAAAAF8/sMsqbVtfIk= >>
    // ----------- >>
    private Project ;

    // ----------- << attribute.annotations@AAAAAAF8/sPJ+blQHJM= >>
    // ----------- >>
    private Set<Researcher>  = new HashSet<>();

    public Set<Researcher> get() {
        return ;
    }

    public Project get() {
        return ;
    }

    public Project get() {
        return ;
    }

    public Set<Researcher> get() {
        return ;
    }

    public void set(Project ) {
        this. = ;
    }

    public void set(Project ) {
        this. = ;
    }

    public void link(Researcher _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void link(Project _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Project _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Researcher _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink(Researcher _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Researcher _, Iterator<Researcher> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(Researcher _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Researcher _, Iterator<Researcher> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF8/r/qwrJQKOM= >>
// ----------- >>
}