/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF8/rskW6oQQwA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF8/rskW6oQQwA= >>
// ----------- >>
public class Researcher extends Employee {
    // ----------- << attribute.annotations@AAAAAAF8/r5rIa9/TdQ= >>
    // ----------- >>
    private String ResearchField;

    // ----------- << attribute.annotations@AAAAAAF8/r0SaK454T8= >>
    // ----------- >>
    private Institute ;

    // ----------- << attribute.annotations@AAAAAAF8/r1Jdq7rWpk= >>
    // ----------- >>
    private Set<Institute>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF8/sAr4bKsD30= >>
    // ----------- >>
    private Set<Project>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF8/sPJ+blRMRc= >>
    // ----------- >>
    private Set<Project>  = new HashSet<>();

    public String getResearchField() {
        return ResearchField;
    }

    public Institute get() {
        return ;
    }

    public Set<Institute> get() {
        return ;
    }

    public Set<Project> get() {
        return ;
    }

    public Set<Project> get() {
        return ;
    }

    public void setResearchField(String ResearchField) {
        this.ResearchField = ResearchField;
    }

    public void set(Institute ) {
        this. = ;
    }

    public void link(Institute _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Institute _) {
        if (_ != null) {
            get().add(_);
        }
    }

    public void link(Project _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void link(Project _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(Institute _) {
        if (_ != null) {
            get().remove(_);
        }
    }

    public void unlink(Iterator<Institute> it) {
        it.remove();
    }

    public void unlink(Project _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Project _, Iterator<Project> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    public void unlink(Project _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Project _, Iterator<Project> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF8/rskW6oQQwA= >>
// ----------- >>
}