/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9D0UMdnBUdtw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9D0UMdnBUdtw= >>
// ----------- >>
public class Commerciante extends Saggio {
    // ----------- << attribute.annotations@AAAAAAF9D0dTaXKmctg= >>
    // ----------- >>
    private int Monete;

    public int getMonete() {
        return Monete;
    }

    public void setMonete(int Monete) {
        this.Monete = Monete;
    }

    // ----------- << method.annotations@AAAAAAF9D1NSmoEp+HE= >>
    // ----------- >>
    public void Forza() {
    // ----------- << method.body@AAAAAAF9D1NSmoEp+HE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAF9D1U0BIn3Zyw= >>
    // ----------- >>
    public void Augment() {
    // ----------- << method.body@AAAAAAF9D1U0BIn3Zyw= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF9D0UMdnBUdtw= >>
// ----------- >>
}