/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9D0n0q3QG7wM= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9D0n0q3QG7wM= >>
// ----------- >>
public class Pozione {
    // ----------- << attribute.annotations@AAAAAAF9D0oTlXROuiI= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAF9D0xQFHXW8Rg= >>
    // ----------- >>
    private void Ingrediente;

    // ----------- << attribute.annotations@AAAAAAF9D057dHbQ9FU= >>
    // ----------- >>
    private Set<Ingredienti>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF9D280CdS/JA8= >>
    // ----------- >>
    private Ingredienti ;

    // ----------- << attribute.annotations@AAAAAAF9D3BRltVepBk= >>
    // ----------- >>
    private Set<Ingredienti>  = new HashSet<>();

    public String getNome() {
        return Nome;
    }

    public void getIngrediente() {
        return Ingrediente;
    }

    public Set<Ingredienti> get() {
        return ;
    }

    public Ingredienti get() {
        return ;
    }

    public Set<Ingredienti> get() {
        return ;
    }

    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    public void setIngrediente(void Ingrediente) {
        this.Ingrediente = Ingrediente;
    }

    public void set(Ingredienti ) {
        this. = ;
    }

    public void link(Ingredienti _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void link(Ingredienti _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Ingredienti _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlink(Ingredienti _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Ingredienti _, Iterator<Ingredienti> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(Ingredienti _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Ingredienti _, Iterator<Ingredienti> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF9D0n0q3QG7wM= >>
// ----------- >>
}