/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9D3BRldVbmM4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9D3BRldVbmM4= >>
// ----------- >>
public class Quantità {
    // ----------- << attribute.annotations@AAAAAAF9D3VYCd2frCI= >>
    // ----------- >>
    private int Quantità;

    public int getQuantità() {
        return Quantità;
    }

    public void setQuantità(int Quantità) {
        this.Quantità = Quantità;
    }

// ----------- << class.extras@AAAAAAF9D3BRldVbmM4= >>
// ----------- >>
}