/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9D0TYv3AGFVg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9D0TYv3AGFVg= >>
// ----------- >>
public class Saggio extends Personaggio {
    // ----------- << attribute.annotations@AAAAAAF9D1A7UHvdh60= >>
    // ----------- >>
    private Libro ;

    // ----------- << attribute.annotations@AAAAAAF9D3j1XOAR+9M= >>
    // ----------- >>
    private Set<Libro>  = new HashSet<>();

    public Libro get() {
        return ;
    }

    public Set<Libro> get() {
        return ;
    }

    public void set(Libro ) {
        this. = ;
    }

    public void link(Libro _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Libro _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(Libro _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Libro _, Iterator<Libro> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    @Override
    // ----------- << method.annotations@AAAAAAF9D1MxgoBuEPs= >>
    // ----------- >>
    public void Forza() {
    // ----------- << method.body@AAAAAAF9D1MxgoBuEPs= >>
    // ----------- >>
    }
    @Override
    // ----------- << method.annotations@AAAAAAF9D1UP54kAkVs= >>
    // ----------- >>
    public void Augment() {
    // ----------- << method.body@AAAAAAF9D1UP54kAkVs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAF9D0TYv3AGFVg= >>
// ----------- >>
}