/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N9oE7zgkXGY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N9oE7zgkXGY= >>
// ----------- >>
public abstract class Documenti {
    // ----------- << attribute.annotations@AAAAAAF9N+fd21CoOxY= >>
    // ----------- >>
    private String NomeDocumento;

    // ----------- << attribute.annotations@AAAAAAF9N+ebeU9WiKE= >>
    // ----------- >>
    private Argomento Argomento;

    // ----------- << attribute.annotations@AAAAAAF9N90MZzrWc0U= >>
    // ----------- >>
    private boolean Prestabile;

    // ----------- << attribute.annotations@AAAAAAF9N9smITi42LY= >>
    // ----------- >>
    private Settori ;

    // ----------- << attribute.annotations@AAAAAAF9N+Dx5Dw/VPk= >>
    // ----------- >>
    private Utente ;

    // ----------- << attribute.annotations@AAAAAAF9N+IjWj+Xedk= >>
    // ----------- >>
    private Scaffali ;

    public String getNomeDocumento() {
        return NomeDocumento;
    }

    public Argomento getArgomento() {
        return Argomento;
    }

    public boolean isPrestabile() {
        return Prestabile;
    }

    public Settori get() {
        return ;
    }

    public Utente get() {
        return ;
    }

    public Scaffali get() {
        return ;
    }

    public void setNomeDocumento(String NomeDocumento) {
        this.NomeDocumento = NomeDocumento;
    }

    public void setArgomento(Argomento Argomento) {
        this.Argomento = Argomento;
    }

    public void setPrestabile(boolean Prestabile) {
        this.Prestabile = Prestabile;
    }

    public void set(Settori ) {
        this. = ;
    }

    public void set(Utente ) {
        this. = ;
    }

    public void set(Scaffali ) {
        this. = ;
    }

    public void link(Settori _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Utente _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Scaffali _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF9N9oE7zgkXGY= >>
// ----------- >>
}