/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N+DWAjux8X0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N+DWAjux8X0= >>
// ----------- >>
public class Prestito {
    // ----------- << attribute.annotations@AAAAAAF9N+QTIUTSHfU= >>
    // ----------- >>
    private String DataInizio;

    // ----------- << attribute.annotations@AAAAAAF9N+RAMUZDN7o= >>
    // ----------- >>
    private String DataFine;

    // ----------- << attribute.annotations@AAAAAAF9N+HDHz7P9i4= >>
    // ----------- >>
    private boolean Rinnovabile;

    public String getDataInizio() {
        return DataInizio;
    }

    public String getDataFine() {
        return DataFine;
    }

    public boolean isRinnovabile() {
        return Rinnovabile;
    }

    public void setDataInizio(String DataInizio) {
        this.DataInizio = DataInizio;
    }

    public void setDataFine(String DataFine) {
        this.DataFine = DataFine;
    }

    public void setRinnovabile(boolean Rinnovabile) {
        this.Rinnovabile = Rinnovabile;
    }

// ----------- << class.extras@AAAAAAF9N+DWAjux8X0= >>
// ----------- >>
}