/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N9uIbjlmWt8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N9uIbjlmWt8= >>
// ----------- >>
public class Scaffali {
    // ----------- << attribute.annotations@AAAAAAF9N9wuIjnqT0s= >>
    // ----------- >>
    private int NumeroScaffale;

    // ----------- << attribute.annotations@AAAAAAF9N+IjWj+YyT8= >>
    // ----------- >>
    private Set<Documento>  = new HashSet<>();

    public int getNumeroScaffale() {
        return NumeroScaffale;
    }

    public Set<Documento> get() {
        return ;
    }

    public void setNumeroScaffale(int NumeroScaffale) {
        this.NumeroScaffale = NumeroScaffale;
    }

    public void link(Documento _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink(Documento _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Documento _, Iterator<Documento> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF9N9uIbjlmWt8= >>
// ----------- >>
}