/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9OK/IOSL3DDY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9OK/IOSL3DDY= >>
// ----------- >>
public class Documento {
    // ----------- << attribute.annotations@AAAAAAF9OLDe+iNRvbE= >>
    // ----------- >>
    private Set<Prestito>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF9OLDyFiObWHU= >>
    // ----------- >>
    private Scaffale ;

    // ----------- << attribute.annotations@AAAAAAF9OLLuGyXnxso= >>
    // ----------- >>
    private Set<Prestito>  = new HashSet<>();

    public Set<Prestito> get() {
        return ;
    }

    public Scaffale get() {
        return ;
    }

    public Set<Prestito> get() {
        return ;
    }

    public void set(Scaffale ) {
        this. = ;
    }

    public void link(Prestito _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Scaffale _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Prestito _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlink(Prestito _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Prestito _, Iterator<Prestito> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(Prestito _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Prestito _, Iterator<Prestito> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF9OK/IOSL3DDY= >>
// ----------- >>
}