/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9OK/RwyMgdrk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9OK/RwyMgdrk= >>
// ----------- >>
public class Prestito {
    // ----------- << attribute.annotations@AAAAAAF9OLDe+iNSNu8= >>
    // ----------- >>
    private Documento ;

    // ----------- << attribute.annotations@AAAAAAF9OLLuGiXmULI= >>
    // ----------- >>
    private Documento ;

    public Documento get() {
        return ;
    }

    public Documento get() {
        return ;
    }

    public void set(Documento ) {
        this. = ;
    }

    public void set(Documento ) {
        this. = ;
    }

    public void link(Documento _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Documento _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF9OK/RwyMgdrk= >>
// ----------- >>
}