/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N5nS5fbChis= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N5nS5fbChis= >>
// ----------- >>
public class Camion extends Automezzo {
    // ----------- << attribute.annotations@AAAAAAF9N6baOQVX7zk= >>
    // ----------- >>
    private int CapacitàQuintali;

    public int getCapacitàQuintali() {
        return CapacitàQuintali;
    }

    public void setCapacitàQuintali(int CapacitàQuintali) {
        this.CapacitàQuintali = CapacitàQuintali;
    }

// ----------- << class.extras@AAAAAAF9N5nS5fbChis= >>
// ----------- >>
}