/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N5ejUfRfV70= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N5ejUfRfV70= >>
// ----------- >>
public class Carta d'identità {
    // ----------- << attribute.annotations@AAAAAAF9N5hJI/WlLAc= >>
    // ----------- >>
    private Float AnnoImmatricolazione;

    // ----------- << attribute.annotations@AAAAAAF9N5htm/XTBHg= >>
    // ----------- >>
    private Float NumeroKm;

    // ----------- << attribute.annotations@AAAAAAF9N5kCq/Y6+7Q= >>
    // ----------- >>
    private String DataUltimaRevisione;

    // ----------- << attribute.annotations@AAAAAAF9N5geqfVV9iU= >>
    // ----------- >>
    private Automezzo ;

    public Float getAnnoImmatricolazione() {
        return AnnoImmatricolazione;
    }

    public Float getNumeroKm() {
        return NumeroKm;
    }

    public String getDataUltimaRevisione() {
        return DataUltimaRevisione;
    }

    public Automezzo get() {
        return ;
    }

    public void setAnnoImmatricolazione(Float AnnoImmatricolazione) {
        this.AnnoImmatricolazione = AnnoImmatricolazione;
    }

    public void setNumeroKm(Float NumeroKm) {
        this.NumeroKm = NumeroKm;
    }

    public void setDataUltimaRevisione(String DataUltimaRevisione) {
        this.DataUltimaRevisione = DataUltimaRevisione;
    }

    public void set(Automezzo ) {
        this. = ;
    }

    public void link(Automezzo _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF9N5ejUfRfV70= >>
// ----------- >>
}