/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N58ma/mZPb4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N58ma/mZPb4= >>
// ----------- >>
public class Contratto {
    // ----------- << attribute.annotations@AAAAAAF9N6Gezf0XN7k= >>
    // ----------- >>
    private Date DataStipula;

    // ----------- << attribute.annotations@AAAAAAF9N6HKRP2uIbc= >>
    // ----------- >>
    private Float Ammontare;

    // ----------- << attribute.annotations@AAAAAAF9N6IBlf5XGPs= >>
    // ----------- >>
    private String DataInizio;

    // ----------- << attribute.annotations@AAAAAAF9N6I5h/7THWU= >>
    // ----------- >>
    private String Dilazioni;

    // ----------- << attribute.annotations@AAAAAAF9N5+GzPnu6xI= >>
    // ----------- >>
    private Clienti ;

    // ----------- << attribute.annotations@AAAAAAF9N8Ligi7KthE= >>
    // ----------- >>
    private Automezzo ;

    public Date getDataStipula() {
        return DataStipula;
    }

    public Float getAmmontare() {
        return Ammontare;
    }

    public String getDataInizio() {
        return DataInizio;
    }

    public String getDilazioni() {
        return Dilazioni;
    }

    public Clienti get() {
        return ;
    }

    public Automezzo get() {
        return ;
    }

    public void setDataStipula(Date DataStipula) {
        this.DataStipula = DataStipula;
    }

    public void setAmmontare(Float Ammontare) {
        this.Ammontare = Ammontare;
    }

    public void setDataInizio(String DataInizio) {
        this.DataInizio = DataInizio;
    }

    public void setDilazioni(String Dilazioni) {
        this.Dilazioni = Dilazioni;
    }

    public void set(Clienti ) {
        this. = ;
    }

    public void set(Automezzo ) {
        this. = ;
    }

    public void link(Clienti _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void link(Automezzo _) {
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

    public void unlink() {
        set(null);
    }

// ----------- << class.extras@AAAAAAF9N58ma/mZPb4= >>
// ----------- >>
}