/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N5nLlfaK/3I= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N5nLlfaK/3I= >>
// ----------- >>
public class Macchina extends Automezzo {
    // ----------- << attribute.annotations@AAAAAAF9N6avXAScbz0= >>
    // ----------- >>
    private int NumeroMaxPersone;

    public int getNumeroMaxPersone() {
        return NumeroMaxPersone;
    }

    public void setNumeroMaxPersone(int NumeroMaxPersone) {
        this.NumeroMaxPersone = NumeroMaxPersone;
    }

// ----------- << class.extras@AAAAAAF9N5nLlfaK/3I= >>
// ----------- >>
}