/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N7eXqx3jVH4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N7eXqx3jVH4= >>
// ----------- >>
public class Optional {
    // ----------- << attribute.annotations@AAAAAAF9N7fK9h7ZUB8= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAF9N7gheR/fyN8= >>
    // ----------- >>
    private Set<Automezzo>  = new HashSet<>();

    public String getNome() {
        return Nome;
    }

    public Set<Automezzo> get() {
        return ;
    }

    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    public void link(Automezzo _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink(Automezzo _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Automezzo _, Iterator<Automezzo> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF9N7eXqx3jVH4= >>
// ----------- >>
}