/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N6NVaQArZJ8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N6NVaQArZJ8= >>
// ----------- >>
public class StoricoMezzo {
    // ----------- << attribute.annotations@AAAAAAF9N6ev3QheLVc= >>
    // ----------- >>
    private String Proprietà;

    // ----------- << attribute.annotations@AAAAAAF9N6PQ9QENq6s= >>
    // ----------- >>
    private Automezzo ;

    public String getProprietà() {
        return Proprietà;
    }

    public Automezzo get() {
        return ;
    }

    public void setProprietà(String Proprietà) {
        this.Proprietà = Proprietà;
    }

    public void set(Automezzo ) {
        this. = ;
    }

    public void link(Automezzo _) {
        if (_ != null) {
            _.get().add(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().get().remove(this);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF9N6NVaQArZJ8= >>
// ----------- >>
}