/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N+VctEgeAAs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N+VctEgeAAs= >>
// ----------- >>
public class Argomento {
    // ----------- << attribute.annotations@AAAAAAF9N+V57kjecIU= >>
    // ----------- >>
    private void Libro;

    // ----------- << attribute.annotations@AAAAAAF9N+Wm50l7HF4= >>
    // ----------- >>
    private void Rivista;

    // ----------- << attribute.annotations@AAAAAAF9N+arMUyhKsM= >>
    // ----------- >>
    private void Materiale audio;

    // ----------- << attribute.annotations@AAAAAAF9N+bKlU0RoJc= >>
    // ----------- >>
    private void Video;

    public void getLibro() {
        return Libro;
    }

    public void getRivista() {
        return Rivista;
    }

    public void getMateriale audio() {
        return Materiale audio;
    }

    public void getVideo() {
        return Video;
    }

    public void setLibro(void Libro) {
        this.Libro = Libro;
    }

    public void setRivista(void Rivista) {
        this.Rivista = Rivista;
    }

    public void setMateriale audio(void Materiale audio) {
        this.Materiale audio = Materiale audio;
    }

    public void setVideo(void Video) {
        this.Video = Video;
    }

// ----------- << class.extras@AAAAAAF9N+VctEgeAAs= >>
// ----------- >>
}enza = Fantascienza;
    }

    public void setMusica(void Musica) {
        this.Musica = Musica;
    }

    public void setAltro(void Altro) {
        this.Altro = Altro;
    }

// ----------- << class.extras@AAAAAAF9N9iFzDZ36xs= >>
// ----------- >>
}