/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N9XXijWIhn0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N9XXijWIhn0= >>
// ----------- >>
public class Biblioteca {
    // ----------- << attribute.annotations@AAAAAAF9N+L3rEK75HA= >>
    // ----------- >>
    private int CodiceBibilioteca;

    // ----------- << attribute.annotations@AAAAAAF9N9YtlDXfMas= >>
    // ----------- >>
    private Set<Settori>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF9N+DWAzu0miU= >>
    // ----------- >>
    private Utente ;

    public int getCodiceBibilioteca() {
        return CodiceBibilioteca;
    }

    public Set<Settori> get() {
        return ;
    }

    public Utente get() {
        return ;
    }

    public void setCodiceBibilioteca(int CodiceBibilioteca) {
        this.CodiceBibilioteca = CodiceBibilioteca;
    }

    public void set(Utente ) {
        this. = ;
    }

    public void link(Settori _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void link(Utente _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink(Settori _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Settori _, Iterator<Settori> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF9N9XXijWIhn0= >>
// ----------- >>
}