/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N9YBfTWzp8c= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N9YBfTWzp8c= >>
// ----------- >>
public class Settori {
    // ----------- << attribute.annotations@AAAAAAF9N9eBEDYwVPw= >>
    // ----------- >>
    private Argomento Argomento;

    // ----------- << attribute.annotations@AAAAAAF9N9YtlTXg2hk= >>
    // ----------- >>
    private Set<Biblioteca>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF9N9smITi589s= >>
    // ----------- >>
    private Set<Documento>  = new HashSet<>();

    public Argomento getArgomento() {
        return Argomento;
    }

    public Set<Biblioteca> get() {
        return ;
    }

    public Set<Documento> get() {
        return ;
    }

    public void setArgomento(Argomento Argomento) {
        this.Argomento = Argomento;
    }

    public void link(Biblioteca _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void link(Documento _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink(Biblioteca _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Biblioteca _, Iterator<Biblioteca> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

    public void unlink(Documento _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Documento _, Iterator<Documento> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF9N9YBfTWzp8c= >>
// ----------- >>
}