/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N5YtafQLjCs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N5YtafQLjCs= >>
// ----------- >>
public abstract class Automezzo {
    // ----------- << attribute.annotations@AAAAAAF9N5ZZlPQ126A= >>
    // ----------- >>
    private String Targa;

    // ----------- << attribute.annotations@AAAAAAF9N5aHG/Q8zCQ= >>
    // ----------- >>
    private int NumeroTelaio;

    // ----------- << attribute.annotations@AAAAAAF9N5bTwfRD3Yg= >>
    // ----------- >>
    private enum Colore;

    // ----------- << attribute.annotations@AAAAAAF9N5cQA/RKGKE= >>
    // ----------- >>
    private Float Cilindrata;

    // ----------- << attribute.annotations@AAAAAAF9N5dHBfRRoXc= >>
    // ----------- >>
    private TipoCarburante TipoCarburante;

    // ----------- << attribute.annotations@AAAAAAF9N6RBqwKPYW4= >>
    // ----------- >>
    private void CapacitàCarico;

    // ----------- << attribute.annotations@AAAAAAF9N5geqfVUW3I= >>
    // ----------- >>
    private Carta d'identità ;

    // ----------- << attribute.annotations@AAAAAAF9N6PQ9QEMdQ8= >>
    // ----------- >>
    private Set<StoricoMezzo>  = new HashSet<>();

    // ----------- << attribute.annotations@AAAAAAF9N7gheR/gHbI= >>
    // ----------- >>
    private Set<Optional>  = new HashSet<>();

    public String getTarga() {
        return Targa;
    }

    private int getNumeroTelaio() {
        return NumeroTelaio;
    }

    public enum getColore() {
        return Colore;
    }

    public Float getCilindrata() {
        return Cilindrata;
    }

    public TipoCarburante getTipoCarburante() {
        return TipoCarburante;
    }

    public void getCapacitàCarico() {
        return CapacitàCarico;
    }

    public Carta d'identità get() {
        return ;
    }

    public Set<StoricoMezzo> get() {
        return ;
    }

    public Set<Optional> get() {
        return ;
    }

    public void setTarga(String Targa) {
        this.Targa = Targa;
    }

    private void setNumeroTelaio(int NumeroTelaio) {
        this.NumeroTelaio = NumeroTelaio;
    }

    public void setColore(enum Colore) {
        this.Colore = Colore;
    }

    public void setCilindrata(Float Cilindrata) {
        this.Cilindrata = Cilindrata;
    }

    public void setTipoCarburante(TipoCarburante TipoCarburante) {
        this.TipoCarburante = TipoCarburante;
    }

    public void setCapacitàCarico(void CapacitàCarico) {
        this.CapacitàCarico = CapacitàCarico;
    }

    public void set(Carta d'identità ) {
        this. = ;
    }

    public void link(Carta d'identità _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(StoricoMezzo _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void link(Optional _) {
        if (_ != null) {
    		_.get().add(this);
            get().add(_);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink(StoricoMezzo _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(StoricoMezzo _, Iterator<StoricoMezzo> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

    public void unlink(Optional _) {
        if (_ != null) {
            _.get().remove(this);
            get().remove(_);
        }
    };

    public void unlink(Optional _, Iterator<Optional> it) {
        if (_ != null) {
            _.get().remove(this);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF9N5YtafQLjCs= >>
// ----------- >>
}