/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N5vqcffXlmo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N5vqcffXlmo= >>
// ----------- >>
public class Clienti {
    // ----------- << attribute.annotations@AAAAAAF9N5y8Yvjmzvg= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAF9N5zZU/kLnsI= >>
    // ----------- >>
    private String Cognome;

    // ----------- << attribute.annotations@AAAAAAF9N5zjnPknfj4= >>
    // ----------- >>
    private String Inidirizzo;

    // ----------- << attribute.annotations@AAAAAAF9N50RcflVLO0= >>
    // ----------- >>
    private void CodiceFiscale;

    // ----------- << attribute.annotations@AAAAAAF9N5+GzPnvecg= >>
    // ----------- >>
    private Set<Contratto>  = new HashSet<>();

    public String getNome() {
        return Nome;
    }

    public String getCognome() {
        return Cognome;
    }

    private String getInidirizzo() {
        return Inidirizzo;
    }

    private void getCodiceFiscale() {
        return CodiceFiscale;
    }

    public Set<Contratto> get() {
        return ;
    }

    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    public void setCognome(String Cognome) {
        this.Cognome = Cognome;
    }

    private void setInidirizzo(String Inidirizzo) {
        this.Inidirizzo = Inidirizzo;
    }

    private void setCodiceFiscale(void CodiceFiscale) {
        this.CodiceFiscale = CodiceFiscale;
    }

    public void link(Contratto _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
            get().add(_);
        }
    }

    public void unlink(Contratto _) {
        if (_ != null) {
            _.set(null);
            get().remove(_);
        }
    }

    public void unlink(Contratto _, Iterator<Contratto> it) {
        if (_ != null) {
            _.set(null);
            it.remove();
        }
    }

// ----------- << class.extras@AAAAAAF9N5vqcffXlmo= >>
// ----------- >>
}