/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9N7UKzBe520w= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9N7UKzBe520w= >>
// ----------- >>
public class TipoCarburante {
    // ----------- << attribute.annotations@AAAAAAF9N7Xe1xofqbg= >>
    // ----------- >>
    private void Elettrico;

    // ----------- << attribute.annotations@AAAAAAF9N7X5wxrn/6E= >>
    // ----------- >>
    private void Gasoliio;

    // ----------- << attribute.annotations@AAAAAAF9N7ZB4Rw0s7o= >>
    // ----------- >>
    private void Benzina;

    public void getElettrico() {
        return Elettrico;
    }

    public void getGasoliio() {
        return Gasoliio;
    }

    public void getBenzina() {
        return Benzina;
    }

    public void setElettrico(void Elettrico) {
        this.Elettrico = Elettrico;
    }

    public void setGasoliio(void Gasoliio) {
        this.Gasoliio = Gasoliio;
    }

    public void setBenzina(void Benzina) {
        this.Benzina = Benzina;
    }

// ----------- << class.extras@AAAAAAF9N7UKzBe520w= >>
// ----------- >>
}