/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9OK+kNCJ8nhc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9OK+kNCJ8nhc= >>
// ----------- >>
public class Scaffale {
    // ----------- << attribute.annotations@AAAAAAF9OLDyFiOaqz8= >>
    // ----------- >>
    private Documento ;

    // ----------- << attribute.annotations@AAAAAAF9OLEFkiP5AbE= >>
    // ----------- >>
    private Settore ;

    public Documento get() {
        return ;
    }

    public Settore get() {
        return ;
    }

    public void set(Documento ) {
        this. = ;
    }

    public void set(Settore ) {
        this. = ;
    }

    public void link(Documento _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Settore _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF9OK+kNCJ8nhc= >>
// ----------- >>
}