/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF9OK+yGSKl8cA= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF9OK+yGSKl8cA= >>
// ----------- >>
public class Settore {
    // ----------- << attribute.annotations@AAAAAAF9OLEFkiP4RNk= >>
    // ----------- >>
    private Scaffale ;

    // ----------- << attribute.annotations@AAAAAAF9OLEbIiRsOv4= >>
    // ----------- >>
    private Biblioteca ;

    public Scaffale get() {
        return ;
    }

    public Biblioteca get() {
        return ;
    }

    public void set(Scaffale ) {
        this. = ;
    }

    public void set(Biblioteca ) {
        this. = ;
    }

    public void link(Scaffale _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Biblioteca _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

// ----------- << class.extras@AAAAAAF9OK+yGSKl8cA= >>
// ----------- >>
}